---
# get-kubectl.yml

- name: Create local temp directory
  local_action:
    module: ansible.builtin.tempfile
    state: directory
    suffix: temp
  register: local_temp_path

- name: Get kubeconfig
  ansible.builtin.fetch:
    src: /home/mrhoads/.kube/config
    dest: '{{ local_temp_path.path }}'

- name: Debug temp path
  local_action:
    module: debug
    msg: '{{ local_temp_path.path }}'

- name: Run Connected Cluster
  local_action:
    module: command
    cmd: az connectedk8s connect --name dev-arc-microk8s03 --resource-group demo-arc-rg --location eastus --kube-config '{{ local_temp_path.path }}/{{ inventory_hostname }}/home/mrhoads/.kube/config'
